# Generated by Django 5.0.6 on 2024-06-08 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_desc',
            field=models.CharField(default=None, max_length=225),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_docs',
            field=models.FileField(default=None, upload_to='patient-docs'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
