# Generated by Django 5.0.6 on 2024-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_appointment_patient_desc_appointment_patient_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_desc',
            field=models.TextField(default=None),
        ),
    ]
